# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('starter', '0005_taskglobalid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagGroup',
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tags', to=settings.AUTH_USER_MODEL, verbose_name='Owner of this tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='descriptive name of the tag'),
        ),
    ]
