# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0006_auto_20161120_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tag', to='starter.Tag')),
                ('parent_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tag', to='starter.Tag')),
            ],
        ),
    ]
