# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('starter', '0008_event_eventglobalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(db_index=True, verbose_name='The type of auth token')),
                ('token', models.CharField(max_length=128, verbose_name='The token given out by the provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL, verbose_name='The user authorized by the token')),
            ],
        ),
        migrations.CreateModel(
            name='StravaActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.IntegerField(db_index=True, unique=True, verbose_name='The id of the activity')),
                ('athlete', models.IntegerField(verbose_name='The strava id of the athlete that performed the activity')),
                ('moving_time', models.IntegerField(verbose_name='The amount of time spent moving')),
                ('elapsed_time', models.IntegerField(verbose_name='The amount of time the total activity took')),
                ('distance', models.FloatField(verbose_name='The total distance of the activity')),
                ('start_date', models.DateTimeField(verbose_name='The time the activity started')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strava_activity', to='starter.Event', verbose_name='The strava activity for this event')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strava_activities', to=settings.AUTH_USER_MODEL, verbose_name='The user that imported the data')),
            ],
        ),
    ]
