# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 00:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('starter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name=b'descriptive name of the tag')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name=b'Title of the task')),
                ('description', models.TextField(max_length=2000, verbose_name=b'Description of the task')),
                ('priority', models.SmallIntegerField(verbose_name=b'The assigned priority of the task')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_tasks', to=settings.AUTH_USER_MODEL, verbose_name=b'Original author of the task')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name=b'Current owner of the task')),
                ('tags', models.ManyToManyField(to='starter.Tag', verbose_name=b'The tags for the task')),
            ],
        ),
    ]
