# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0003_auto_20161017_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='descriptive name of the tag group')),
            ],
        ),
    ]
