# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0011_eventtags_taskevents_tasktags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_duration_secs',
            field=models.IntegerField(default=0, verbose_name='Expected duration of the task in seconds'),
            preserve_default=False,
        ),
    ]
