# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0013_auto_20170801_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Time that the task is due'),
        ),
    ]
