# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('starter', '0014_task_due_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=65536, verbose_name='Content of the capture')),
                ('creation_time', models.DateTimeField(verbose_name='Creation time of the capture')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_captures', to=settings.AUTH_USER_MODEL, verbose_name='Original author of the capture')),
            ],
        ),
        migrations.CreateModel(
            name='CaptureGlobalId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField(db_index=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_user', to='starter.Capture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_captures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
