# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0015_capture_captureglobalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state_updated_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Time that the task last had its state changed'),
        ),
    ]
