# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-31 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0016_task_state_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='', max_length=64, verbose_name='css color value'),
        ),
    ]
