# Generated by Django 2.2.3 on 2019-07-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0017_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(through='starter.EventTags', to='starter.Tag', verbose_name='The tags for the event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='events',
            field=models.ManyToManyField(through='starter.TaskEvents', to='starter.Event', verbose_name='The events for this task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(through='starter.TaskTags', to='starter.Tag', verbose_name='The tags for the task'),
        ),
    ]
